# Generated by Django 6.0.4 on 2026-06-23 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('agente', 'Agente')], max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='propiedades/')),
                ('direccion', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Local', 'Local')], max_length=20)),
                ('operacion', models.CharField(choices=[('Renta', 'Renta'), ('Venta', 'Venta')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estacionamiento', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('rentada', 'Rentada'), ('vendida', 'Vendida')], default='disponible', max_length=15)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquilino', models.CharField(max_length=100)),
                ('archivo_pdf', models.FileField(upload_to='contratos/')),
                ('fecha_firma', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('plazo_meses', models.IntegerField()),
                ('aval_requerido', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.propiedad')),
            ],
        ),
    ]
