# Generated by Django 6.0.5 on 2026-06-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('mes_correspondiente', models.DateField(help_text='Primer día del mes que cubre este pago')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='inmobiliaria.contrato')),
            ],
            options={
                'verbose_name': 'Pago de Renta',
                'verbose_name_plural': 'Pagos de Rentas',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
