# Generated by Django 6.0.4 on 2026-06-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria', '0002_pagorenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagorenta',
            name='mes_correspondiente',
            field=models.DateField(),
        ),
    ]
